calling bottle thru script: make load_app() work
For example, if you call a python script that launches
bottle, it is the path of the script that gets added
to sys.path, *not* the current directory. But it is
with respect to the current directory that I would like
to specify the value for `app`:

https://github.com/bottlepy/bottle/blob/0.12.8/bottle.py#L3044-L3045

This makes it so that the application/target can be found,
if it is in the current directory, even if you are
calling another script somewhere else that ultimately
hands over to bottle, and thus the load_app() function

The error avoided is:

ImportError: No module named my_app

When I execute a script that passes the value "my_app"
to bottle.run(app=value)